package schema

import (
	"time"

	"github.com/uptrace/bun"
)

type OrderDetailsSchema struct {
	// テーブル名とエイリアスを設定
	bun.BaseModel `bun:"table:order_details,alias:od"`

	// id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	ID int64 `bun:"id,pk,autoincrement"`

	// order_id BIGINT NOT NULL (外部キー)
	OrderID int64 `bun:"order_id,notnull"`

	// product_name VARCHAR NOT NULL
	ProductName string `bun:"product_name,notnull"`

	// price NUMERIC(10,2) NOT NULL
	Price float64 `bun:"price,notnull"`

	// created_at TIMESTAMPTZ NOT NULL DEFAULT now()
	CreatedAt time.Time `bun:"created_at,notnull,default:current_timestamp"`

	// updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
	UpdatedAt time.Time `bun:"updated_at,notnull,default:current_timestamp"`

	// リレーションの設定
	Order *OrdersSchema `bun:"rel:belongs-to,join:order_id=id"`
}
