package schema

import (
	"time"

	"github.com/uptrace/bun"
)

type OrdersSchema struct {
	// テーブル名とエイリアスを設定
	bun.BaseModel `bun:"table:orders,alias:o"`

	// id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	ID int64 `bun:"id,pk,autoincrement"`

	// order_no VARCHAR NOT NULL UNIQUE
	OrderNo string `bun:"order_no,notnull,unique"`

	// customer_id BIGINT NOT NULL
	CustomerID int64 `bun:"customer_id,notnull"`

	// total_amount NUMERIC(12,2) NOT NULL
	TotalAmount float64 `bun:"total_amount,notnull"`

	// created_at TIMESTAMPTZ NOT NULL DEFAULT now()
	CreatedAt time.Time `bun:"created_at,notnull,default:current_timestamp"`

	// updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
	UpdatedAt time.Time `bun:"updated_at,notnull,default:current_timestamp"`

	// リレーションの設定
	Customer     *UsersSchema          `bun:"rel:belongs-to,join:customer_id=id"`
	OrderDetails []*OrderDetailsSchema `bun:"rel:has-many,join:id=order_id"`
}
