package schema

import (
	"time"

	"github.com/uptrace/bun"
)

type UserSchema struct {
	// テーブル名とエイリアスを設定
	bun.BaseModel `bun:"table:users,alias:u"`

	// BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
	ID int64 `bun:"id,pk,autoincrement"`

	// VARCHAR NOT NULL
	Name string `bun:"name,notnull"`

	// VARCHAR NOT NULL UNIQUE
	Email string `bun:"email,notnull,unique"`

	// TIMESTAMPTZ NOT NULL DEFAULT now()
	CreatedAt time.Time `bun:"created_at,notnull,default:current_timestamp"`

	// TIMESTAMPTZ NOT NULL DEFAULT now()
	UpdatedAt time.Time `bun:"updated_at,notnull,default:current_timestamp"`
}
