-- 1. order_detailsテーブルの作成
CREATE TABLE order_details (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  product_name VARCHAR NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_order_details_order
    FOREIGN KEY (order_id)
    REFERENCES orders(id)
);

-- 2. order_detailsテーブルの「updated_at」を自動更新するトリガー設定
CREATE TRIGGER update_order_details_updated_at
BEFORE UPDATE ON order_details
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
